### ISSUE TITLE
[Rio de Janeiro] Global AI Bootcamp

### ISSUE THREAD

**Issue by glaucia86** [datascience-br/eventos#1]
**Título**: Global AI Bootcamp Rio de Janeiro
  
**Data**: Em breve mais informações

**Local**: Centro, Rio de Janeiro - Infnet

**Descrição (breve)**:
O Global AI Bootcamp é um evento gratuito de um dia organizado por comunidades locais de todo o mundo que são apaixonadas por Inteligência Artificial ligadas as stacks da Microsoft.
Durante este Bootcamp de IA, você se inspirará em sessões e teremos muitos hands-on  durante as oficinas. No final do dia, você será capaz de criar seu próprios aplicativos fazendo uso de recursos de IA.

**Logotipo do evento**: 
![alt text](https://i.imgsafe.org/ee/eecebd1d7e.png)

**Valor**: Gratuito

**Mais informações**: 
Todos aprenderão a como implementar soluções inteligentes fazendo uso da plataforma da Microsoft IA, incluindo serviços IA Cognitivos, Bot Framework, bem como ferramentas de aprendizagem fazendo uso do Azure Machine Learning, Ferramentas do Visual Studio Code para IA e Kit de Ferramentas para IA.

**[LINK DO EVENTO](https://www.globalaibootcamp.com/bootcamp/6c701b9d-9516-463b-b6e1-4c2e92aeb83d)**

**Transmissão ao vivo**: Não

**O conteúdo será gravado**: Não

**Comment by italojs** [comment]
Dentro de algumas horas a página será atualizada
