### ISSUE TITLE
[Belo Horizonte] Bootcamp Data Science Minerando Dados

### ISSUE THREAD

**Issue by felipesf05** [datascience-br/eventos#2]
**Título**: Bootcamp Data Science Minerando Dados
  
**Data**: 17,18 de Novembro

**Local**: Castelo de Alcazar, 125, Castelo – BH/MG

**Descrição (breve)**: Bootcamp em Data Sciente para você mergulhar nos dados e aprender a extrair insights valiosos. Alavanque a sua carreira como Cientista de Dados.

**Logotipo do evento**: 
![bootcamp-md](https://user-images.githubusercontent.com/3044244/48642041-dae26f00-e9c2-11e8-87af-7d41eae532d8.png)

**Valor**: 899,90

**Mais informações**: https://bootcamp-mdbh.landen.co/

**Transmissão ao vivo**: Sim (instagram) https://www.instagram.com/blogminerando

**O conteúdo será gravado**: Não

**Comment by italojs** [comment]
Dentro de algumas horas a página será atualizada
