### ISSUE TITLE
[Campos dos Goytacazes] Bootcamp Data Science Minerando Dados

### ISSUE THREAD

**Issue by felipesf05** [datascience-br/eventos#3]
**Título**: Bootcamp Data Science Minerando Dados
  
**Data**: 07,08 de Dezembro

**Local**: Campos dos Goytacazes - RJ

**Descrição (breve)**: Bootcamp em Data Sciente para você mergulhar nos dados e aprender a extrair insights valiosos. Alavanque a sua carreira como Cientista de Dados.

**Logotipo do evento**: 
![bootcamp-md](https://user-images.githubusercontent.com/3044244/48642041-dae26f00-e9c2-11e8-87af-7d41eae532d8.png)

**Valor**: 899,90

**Mais informações**: https://www.sympla.com.br/sobre-o-evento?id=367940

**Transmissão ao vivo**: Sim (instagram) https://www.instagram.com/blogminerando

**O conteúdo será gravado**: Não

**Comment by italojs** [comment]
Qual o endereço do evento?
O link  https://www.sympla.com.br/sobre-o-evento?id=367940 redireciona para a página de login

**Comment by felipesf05** [comment]
Desculpe o engano, segue os dados.
Link do evento: https://www.sympla.com.br/bootcamp-data-science-minerando-dados__367940
Endereço: Teccampos, Avenida Alberto Lamego, 2000, Campus da Uenf, Cent, Parque Califórnia
Campos dos Goytacazes, RJ

**Comment by italojs** [comment]
Dentro de algumas horas a página será atualizada com seu evento :)
