### ISSUE TITLE
[Recife] III Workshop de Mineração de Dados

### ISSUE THREAD

**Issue by diegoelages** [datascience-br/eventos#4]
**Título**:  III Workshop de Mineração de Dados
  
**Data**: 30/11/2018 08:30 - 19:00

**Local**: POLI - Escola Politécnica de Pernambuco

**Descrição (breve)**: O Workshop de Mineração de Dados continua crescendo, está partindo para a sua 3ª Edição, trazendo uma boa variedade de conteúdo com trabalho sobre o estudo e aplicação de Mineração de Dados na solução de problemas sociais, governamentais, industriais e educacionais.

**Logotipo do evento**: 

**Valor**: Gratuito

**Mais informações**: https://www.facebook.com/events/340328116742368/?ti=cl

**Transmissão ao vivo**: Não

**O conteúdo será gravado**: Não

**Comment by italojs** [comment]
Desculpe a demora, estava um tanto quanto desconectado do mundo virtual essa ultima semana, o evento foi pubilcado na página :)
